import { useEffect } from 'react';
import { useDiagnostic, ACTIONS } from '../context/DiagnosticContext';
import { parseDTCLookup } from '../utils/dtcLookupParser';
import { parseCompareTable } from '../utils/compareParser';
import { parseDreNames } from '../utils/dreParser';

// ─── Pre-generated module bundles (populated by vf-processor.js) ─────────────

/**
 * Auto-discovers all DTC lookup modules pre-generated by vf-processor.js.
 * Each module exports { [dtcCode]: { enableCondition, … } }.
 */
const dtcAutoModules = import.meta.glob('../data/dtc-auto/*.js', { eager: true });

/**
 * Auto-discovers all DRE name modules pre-generated by vf-processor.js.
 * Each module exports { [ECU_NAME_UPPERCASE]: "DRE Person Name" }.
 */
const dreAutoModules = import.meta.glob('../data/dre-auto/*.js', { eager: true });

function mergeModules(modules) {
  return Object.values(modules).reduce((acc, mod) => {
    return typeof mod.default === 'object' && mod.default !== null
      ? { ...acc, ...mod.default }
      : acc;
  }, {});
}

// ─── Compare Table: try all known filename variants ───────────────────────────

/**
 * All accepted Compare Table filename variants (URL-encoded where needed).
 * The browser fetches each with a HEAD request to check existence and
 * Last-Modified timestamp, then GETs the most-recently-modified one.
 */
const COMPARE_TABLE_NAMES = [
  '/Compare%20Table.xlsx',   // "Compare Table.xlsx"  (space encoded)
  '/CompareTable.xlsx',
  '/Compare_Table.xlsx',
  '/Compare_Tables.xlsx',
];

/**
 * Returns the URL of the most recently modified Compare Table file found in
 * /public, or null if none of the candidates exist.
 */
async function findMostRecentCompareTable() {
  const results = await Promise.all(
    COMPARE_TABLE_NAMES.map(async (path) => {
      try {
        const res = await fetch(path, { method: 'HEAD' });
        if (!res.ok) return null;
        const lastModified = res.headers.get('Last-Modified');
        const ts = lastModified ? new Date(lastModified).getTime() : 0;
        return { path, ts };
      } catch {
        return null;
      }
    })
  );

  const found = results.filter(Boolean);
  if (!found.length) return null;

  // Pick the file with the newest Last-Modified timestamp.
  // Ties (e.g. server doesn't send Last-Modified) resolve to whichever
  // appears first in COMPARE_TABLE_NAMES.
  return found.reduce((best, curr) => (curr.ts > best.ts ? curr : best)).path;
}

// ─── Hook ─────────────────────────────────────────────────────────────────────

/**
 * Loads static reference data into global state on mount:
 *
 * DTC lookup priority (later entries win on key conflicts):
 *   1. /public/DTCs/DTC.xlsx  — base file, browser-side parse
 *   2. src/data/dtc-auto/     — pre-parsed modules from vf-processor (supplement / override)
 *
 * Compare Table:
 *   Tries "Compare Table.xlsx", "CompareTable.xlsx", "Compare_Table.xlsx",
 *   "Compare_Tables.xlsx" — uses the most recently modified one.
 *
 * DRE Names priority (later source wins on key conflicts):
 *   1. src/data/dre-auto/  — pre-parsed modules from vf-processor
 *   2. /public/DRE Names.xlsx — direct browser fetch (fallback)
 */
export function useStaticFilesLoader() {
  const { dispatch } = useDiagnostic();

  useEffect(() => {
    async function load() {
      // ── 1: seed DTC lookup from /public/DTCs/DTC.xlsx ─────────────────────
      try {
        const res = await fetch('/DTCs/DTC.xlsx');
        if (res.ok) {
          const buf = await res.arrayBuffer();
          dispatch({ type: ACTIONS.SET_DTC_LOOKUP, payload: parseDTCLookup(buf) });
        }
      } catch { /* absent — ignore */ }

      // ── 2: merge pre-generated DTC modules (vf-processor output) ──────────
      const autoMergedDtc = mergeModules(dtcAutoModules);
      if (Object.keys(autoMergedDtc).length > 0) {
        dispatch({ type: ACTIONS.MERGE_DTC_LOOKUP, payload: autoMergedDtc });
      }

      // ── 3: load Compare Table (whichever variant exists, newest wins) ──────
      try {
        const comparePath = await findMostRecentCompareTable();
        if (comparePath) {
          const res = await fetch(comparePath);
          if (res.ok) {
            const buf = await res.arrayBuffer();
            dispatch({ type: ACTIONS.SET_COMPARE_DATA, payload: parseCompareTable(buf) });
          }
        }
      } catch { /* absent — ignore */ }

      // ── 4a: load DRE names from pre-generated modules (vf-processor) ───────
      const autoMergedDre = mergeModules(dreAutoModules);
      if (Object.keys(autoMergedDre).length > 0) {
        dispatch({ type: ACTIONS.SET_DRE_DATA, payload: autoMergedDre });
      } else {
        // ── 4b: fallback — fetch /public/DRE Names.xlsx directly ─────────────
        try {
          const res = await fetch('/DRE%20Names.xlsx');
          if (res.ok) {
            const buf = await res.arrayBuffer();
            dispatch({ type: ACTIONS.SET_DRE_DATA, payload: parseDreNames(buf) });
          }
        } catch { /* absent — ignore */ }
      }
    }

    load();
  }, [dispatch]);
}
