import { useEffect } from 'react';
import { useDiagnostic, ACTIONS } from '../context/DiagnosticContext';
import { parseDTCLookup } from '../utils/dtcLookupParser';
import { parseCompareTable } from '../utils/compareParser';

/**
 * Auto-discovers all DTC lookup modules pre-generated by vf-processor.js.
 * Each module exports a lookup object { [dtcCode]: { enableCondition, ... } }.
 * Evaluated eagerly at build time by Vite; HMR picks up new files during dev.
 */
const dtcAutoModules = import.meta.glob('../data/dtc-auto/*.js', { eager: true });

/**
 * Merges all auto-generated DTC modules into a single lookup map.
 * Returns an empty object if no modules have been generated yet.
 */
function mergeAutoModules() {
  return Object.values(dtcAutoModules).reduce((acc, mod) => {
    return typeof mod.default === 'object' && mod.default !== null
      ? { ...acc, ...mod.default }
      : acc;
  }, {});
}

/**
 * Fetches DTC.xlsx and CompareTable.xlsx from /public on mount and
 * loads them into global state.
 *
 * DTC lookup priority (later entries win on key conflicts):
 *   1. /public/DTC.xlsx   — base file, parsed in-browser (fallback / backward compat)
 *   2. src/data/dtc-auto/ — pre-parsed modules from vf-processor (supplement / override)
 *
 * This means running `npm run dev:full` enriches the lookup with any
 * additional DTC*.xlsx files dropped in /public, on top of the base file.
 */
export function useStaticFilesLoader() {
  const { dispatch } = useDiagnostic();

  useEffect(() => {
    async function load() {
      // ── Step 1: seed from /public/DTC.xlsx (browser-side parse, backward compat) ──
      try {
        const res = await fetch('/DTCs/DTC.xlsx');
        if (res.ok) {
          const buf = await res.arrayBuffer();
          dispatch({ type: ACTIONS.SET_DTC_LOOKUP, payload: parseDTCLookup(buf) });
        }
      } catch { /* file absent — ignore */ }

      // ── Step 2: merge any auto-generated DTC modules (from vf-processor) ──
      const autoMerged = mergeAutoModules();
      if (Object.keys(autoMerged).length > 0) {
        dispatch({ type: ACTIONS.MERGE_DTC_LOOKUP, payload: autoMerged });
      }

      // ── Step 3: load CompareTable from /public ──
      try {
        const res = await fetch('/CompareTable.xlsx');
        if (res.ok) {
          const buf = await res.arrayBuffer();
          dispatch({ type: ACTIONS.SET_COMPARE_DATA, payload: parseCompareTable(buf) });
        }
      } catch { /* file absent — ignore */ }
    }

    load();
  }, [dispatch]);
}
